import type grapesjs from "grapesjs"

/* Metadata exported for the custom React sidebar.
 * Keeping this in sync with the actual block definitions avoids
 * hard-coding IDs in the UI component. */

export interface BlockMeta {
  id: string
  label: string
  category: string
  content: string
}

export const BLOCKS_META: BlockMeta[] = [
  /* ── Headers ── */
  { id: "header-1", label: "Classic Nav", category: "Header", content: `<header class="w-full bg-white border-b border-gray-200 px-6 py-4 flex items-center justify-between"><div class="text-2xl font-black text-gray-900 tracking-tight">Logo</div><nav class="flex gap-8 text-sm font-medium text-gray-600"><a href="#" class="hover:text-gray-900">Shop</a><a href="#" class="hover:text-gray-900">About</a><a href="#" class="hover:text-gray-900">Contact</a></nav></header>` },
  { id: "header-2", label: "Centered Nav", category: "Header", content: `<header class="w-full bg-white border-b border-gray-200 py-6 text-center"><div class="text-3xl font-black text-gray-900 mb-4 tracking-tight">Brand</div><nav class="flex justify-center gap-8 text-sm font-medium text-gray-600"><a href="#" class="hover:text-gray-900">Home</a><a href="#" class="hover:text-gray-900">Collection</a><a href="#" class="hover:text-gray-900">Lookbook</a><a href="#" class="hover:text-gray-900">Contact</a></nav></header>` },
  { id: "header-3", label: "Minimal", category: "Header", content: `<header class="w-full bg-white px-6 py-4 flex items-center justify-between"><div class="text-xl font-bold text-gray-900">Studio</div><button class="text-gray-900 p-2"><svg class="w-6 h-6" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16"/></svg></button></header>` },
  { id: "header-4", label: "Overlay", category: "Header", content: `<header class="w-full absolute top-0 left-0 z-50 px-6 py-4 flex items-center justify-between bg-transparent"><div class="text-2xl font-black text-white tracking-tight">Luxe</div><nav class="flex gap-8 text-sm font-medium text-white/80"><a href="#" class="hover:text-white">Shop</a><a href="#" class="hover:text-white">Story</a><a href="#" class="hover:text-white">Contact</a></nav></header>` },
  { id: "header-5", label: "Mega Menu", category: "Header", content: `<header class="w-full bg-gray-900 text-white px-6 py-4 flex items-center justify-between"><div class="text-xl font-bold">Marketplace</div><nav class="flex gap-6 text-sm"><a href="#" class="hover:text-gray-300">Categories</a><a href="#" class="hover:text-gray-300">Deals</a><a href="#" class="hover:text-gray-300">Sellers</a><a href="#" class="hover:text-gray-300">Support</a></nav><div class="text-sm font-medium">Cart (0)</div></header>` },

  /* ── Heroes ── */
  { id: "hero-1", label: "Split Hero", category: "Hero", content: `<section class="w-full bg-gray-50"><div class="max-w-7xl mx-auto grid md:grid-cols-2 gap-0 min-h-[500px]"><div class="flex flex-col justify-center px-8 py-16 md:px-16"><h1 class="text-4xl md:text-6xl font-black text-gray-900 leading-tight mb-6">The Modern Standard</h1><p class="text-lg text-gray-600 mb-8">Clean, fast, and designed for growth.</p><a href="#" class="inline-block bg-black text-white px-8 py-3 rounded-lg font-medium text-center hover:bg-gray-800">Shop Now</a></div><div class="bg-gray-200 min-h-[300px] flex items-center justify-center"><span class="text-gray-400 text-sm">Hero Image</span></div></div></section>` },
  { id: "hero-2", label: "Centered Hero", category: "Hero", content: `<section class="w-full bg-white text-center py-24 px-6"><h1 class="text-5xl md:text-7xl font-black text-gray-900 tracking-tight mb-6">Built for Scale</h1><p class="text-xl text-gray-500 max-w-2xl mx-auto mb-10">A curated platform for modern merchants.</p><div class="flex justify-center gap-4"><a href="#" class="bg-black text-white px-8 py-3 rounded-lg font-medium hover:bg-gray-800">Get Started</a><a href="#" class="border border-gray-300 text-gray-900 px-8 py-3 rounded-lg font-medium hover:border-gray-900">Learn More</a></div></section>` },
  { id: "hero-3", label: "Background Image", category: "Hero", content: `<section class="w-full relative bg-gray-900 text-white py-32 px-6 text-center overflow-hidden"><div class="absolute inset-0 bg-black/50 z-0"></div><div class="relative z-10 max-w-3xl mx-auto"><h1 class="text-4xl md:text-6xl font-black mb-6">Experience Luxury</h1><p class="text-lg text-white/80 mb-10">Handpicked essentials for the elevated life.</p><a href="#" class="inline-block bg-white text-black px-8 py-3 rounded-lg font-medium hover:bg-gray-100">Explore</a></div><div class="absolute inset-0 flex items-center justify-center z-0"><span class="text-gray-500 text-sm">Background Image</span></div></section>` },
  { id: "hero-4", label: "Feature Columns", category: "Hero", content: `<section class="w-full bg-gray-50 py-20 px-6"><div class="max-w-7xl mx-auto grid md:grid-cols-2 gap-12 items-center"><div><span class="text-sm font-bold text-blue-600 uppercase tracking-wider mb-4 block">New Arrivals</span><h1 class="text-4xl md:text-5xl font-black text-gray-900 leading-tight mb-6">Redefine Your Workspace</h1><p class="text-gray-600 mb-8">Premium tools and furniture designed to inspire.</p><a href="#" class="bg-black text-white px-8 py-3 rounded-lg font-medium inline-block hover:bg-gray-800">Shop Collection</a></div><div class="grid grid-cols-2 gap-4"><div class="bg-gray-200 rounded-2xl h-40 flex items-center justify-center"><span class="text-gray-400 text-xs">Img 1</span></div><div class="bg-gray-200 rounded-2xl h-40 flex items-center justify-center mt-8"><span class="text-gray-400 text-xs">Img 2</span></div></div></div></section>` },
  { id: "hero-5", label: "Video Hero", category: "Hero", content: `<section class="w-full relative bg-gray-900 text-white overflow-hidden"><div class="aspect-video w-full bg-gray-800 flex items-center justify-center"><span class="text-gray-500 text-sm">Video Background</span></div><div class="absolute inset-0 flex items-center justify-center bg-black/40"><div class="text-center px-6"><h1 class="text-4xl md:text-6xl font-black mb-6">Motion. Design. Life.</h1><a href="#" class="inline-block bg-white text-black px-8 py-3 rounded-lg font-medium hover:bg-gray-100">Shop Now</a></div></div></section>` },

  /* ── Products ── */
  { id: "products-1", label: "Product Grid", category: "Products", content: `<section class="w-full bg-white py-16 px-6"><div class="max-w-7xl mx-auto"><div class="flex justify-between items-end mb-10"><h2 class="text-3xl font-bold text-gray-900">Featured Products</h2><a href="#" class="text-sm font-medium text-gray-500 hover:text-gray-900">View all</a></div><div class="grid grid-cols-2 md:grid-cols-4 gap-6"><div class="group"><div class="aspect-square bg-gray-100 rounded-2xl mb-4 flex items-center justify-center"><span class="text-gray-300 text-xs">Product</span></div><h3 class="font-medium text-gray-900 mb-1">Product Name</h3><p class="text-sm text-gray-500">$0.00</p></div><div class="group"><div class="aspect-square bg-gray-100 rounded-2xl mb-4 flex items-center justify-center"><span class="text-gray-300 text-xs">Product</span></div><h3 class="font-medium text-gray-900 mb-1">Product Name</h3><p class="text-sm text-gray-500">$0.00</p></div><div class="group"><div class="aspect-square bg-gray-100 rounded-2xl mb-4 flex items-center justify-center"><span class="text-gray-300 text-xs">Product</span></div><h3 class="font-medium text-gray-900 mb-1">Product Name</h3><p class="text-sm text-gray-500">$0.00</p></div><div class="group"><div class="aspect-square bg-gray-100 rounded-2xl mb-4 flex items-center justify-center"><span class="text-gray-300 text-xs">Product</span></div><h3 class="font-medium text-gray-900 mb-1">Product Name</h3><p class="text-sm text-gray-500">$0.00</p></div></div></div></section>` },
  { id: "products-2", label: "Featured + Text", category: "Products", content: `<section class="w-full bg-gray-50 py-16 px-6"><div class="max-w-7xl mx-auto grid md:grid-cols-2 gap-12 items-center"><div class="bg-gray-200 rounded-3xl aspect-square flex items-center justify-center"><span class="text-gray-400 text-sm">Featured Image</span></div><div><span class="text-sm font-bold text-blue-600 uppercase tracking-wider mb-3 block">Editor's Pick</span><h2 class="text-3xl md:text-4xl font-bold text-gray-900 mb-4">The Essential</h2><p class="text-gray-600 mb-8">A timeless piece crafted with precision and care.</p><a href="#" class="inline-block bg-black text-white px-8 py-3 rounded-lg font-medium hover:bg-gray-800">Shop Now</a></div></div></section>` },
  { id: "products-3", label: "Carousel Row", category: "Products", content: `<section class="w-full bg-white py-16 px-6"><div class="max-w-7xl mx-auto"><h2 class="text-3xl font-bold text-gray-900 mb-10">Trending Now</h2><div class="flex gap-6 overflow-x-auto pb-4"><div class="min-w-[220px]"><div class="w-[220px] aspect-[3/4] bg-gray-100 rounded-2xl mb-4 flex items-center justify-center"><span class="text-gray-300 text-xs">Product</span></div><h3 class="font-medium text-gray-900 mb-1">Product Name</h3><p class="text-sm text-gray-500">$0.00</p></div><div class="min-w-[220px]"><div class="w-[220px] aspect-[3/4] bg-gray-100 rounded-2xl mb-4 flex items-center justify-center"><span class="text-gray-300 text-xs">Product</span></div><h3 class="font-medium text-gray-900 mb-1">Product Name</h3><p class="text-sm text-gray-500">$0.00</p></div><div class="min-w-[220px]"><div class="w-[220px] aspect-[3/4] bg-gray-100 rounded-2xl mb-4 flex items-center justify-center"><span class="text-gray-300 text-xs">Product</span></div><h3 class="font-medium text-gray-900 mb-1">Product Name</h3><p class="text-sm text-gray-500">$0.00</p></div></div></div></section>` },
  { id: "products-4", label: "Category Grid", category: "Products", content: `<section class="w-full bg-white py-16 px-6"><div class="max-w-7xl mx-auto"><h2 class="text-3xl font-bold text-gray-900 mb-10">Shop by Category</h2><div class="grid grid-cols-2 md:grid-cols-3 gap-6"><a href="#" class="relative rounded-2xl overflow-hidden aspect-[4/3] bg-gray-200 flex items-center justify-center"><span class="text-gray-400 text-xs">Image</span><div class="absolute inset-0 bg-black/30 flex items-center justify-center"><span class="text-white font-bold text-lg">Electronics</span></div></a><a href="#" class="relative rounded-2xl overflow-hidden aspect-[4/3] bg-gray-200 flex items-center justify-center"><span class="text-gray-400 text-xs">Image</span><div class="absolute inset-0 bg-black/30 flex items-center justify-center"><span class="text-white font-bold text-lg">Home</span></div></a><a href="#" class="relative rounded-2xl overflow-hidden aspect-[4/3] bg-gray-200 flex items-center justify-center"><span class="text-gray-400 text-xs">Image</span><div class="absolute inset-0 bg-black/30 flex items-center justify-center"><span class="text-white font-bold text-lg">Fashion</span></div></a><a href="#" class="relative rounded-2xl overflow-hidden aspect-[4/3] bg-gray-200 flex items-center justify-center"><span class="text-gray-400 text-xs">Image</span><div class="absolute inset-0 bg-black/30 flex items-center justify-center"><span class="text-white font-bold text-lg">Sports</span></div></a><a href="#" class="relative rounded-2xl overflow-hidden aspect-[4/3] bg-gray-200 flex items-center justify-center"><span class="text-gray-400 text-xs">Image</span><div class="absolute inset-0 bg-black/30 flex items-center justify-center"><span class="text-white font-bold text-lg">Beauty</span></div></a><a href="#" class="relative rounded-2xl overflow-hidden aspect-[4/3] bg-gray-200 flex items-center justify-center"><span class="text-gray-400 text-xs">Image</span><div class="absolute inset-0 bg-black/30 flex items-center justify-center"><span class="text-white font-bold text-lg">Food</span></div></a></div></div></section>` },
  { id: "products-5", label: "Highlight CTA", category: "Products", content: `<section class="w-full bg-black text-white py-20 px-6"><div class="max-w-7xl mx-auto flex flex-col md:flex-row items-center gap-12"><div class="flex-1"><h2 class="text-4xl md:text-5xl font-black mb-6">The Limited Edition</h2><p class="text-white/70 text-lg mb-8">Only 100 units. Signed and numbered.</p><a href="#" class="inline-block bg-white text-black px-8 py-3 rounded-lg font-medium hover:bg-gray-100">Reserve Yours</a></div><div class="flex-1 bg-gray-800 rounded-3xl aspect-square w-full max-w-md flex items-center justify-center"><span class="text-gray-500 text-sm">Product Image</span></div></div></section>` },

  /* ── Text ── */
  { id: "text-1", label: "Large Statement", category: "Text", content: `<section class="w-full bg-white py-20 px-6"><div class="max-w-5xl mx-auto"><h2 class="text-4xl md:text-6xl font-black text-gray-900 leading-tight mb-8">We build tools that help independent businesses thrive.</h2><p class="text-xl text-gray-500 max-w-2xl">No setup fees, no hidden costs.</p></div></section>` },
  { id: "text-2", label: "3-Column Features", category: "Text", content: `<section class="w-full bg-gray-50 py-16 px-6"><div class="max-w-7xl mx-auto grid md:grid-cols-3 gap-10"><div><h3 class="text-lg font-bold text-gray-900 mb-3">Fast Shipping</h3><p class="text-gray-500 text-sm leading-relaxed">Free 2-day delivery on all orders over $50.</p></div><div><h3 class="text-lg font-bold text-gray-900 mb-3">Secure Checkout</h3><p class="text-gray-500 text-sm leading-relaxed">256-bit encryption keeps your data safe.</p></div><div><h3 class="text-lg font-bold text-gray-900 mb-3">24/7 Support</h3><p class="text-gray-500 text-sm leading-relaxed">Talk to a real human, any time of day.</p></div></div></section>` },
  { id: "text-3", label: "Quote Block", category: "Text", content: `<section class="w-full bg-white py-20 px-6 text-center"><div class="max-w-3xl mx-auto"><svg class="w-10 h-10 text-gray-200 mx-auto mb-6" fill="currentColor" viewBox="0 0 24 24"><path d="M14.017 21v-7.391c0-5.704 3.731-9.57 8.983-10.609l.995 2.151c-2.432.917-3.995 3.638-3.995 5.849h4v10h-9.983zm-14.017 0v-7.391c0-5.704 3.748-9.57 9-10.609l.996 2.151c-2.433.917-3.996 3.638-3.996 5.849h3.983v10h-9.983z"/></svg><blockquote class="text-2xl md:text-3xl font-medium text-gray-900 leading-snug mb-8">This platform completely changed how we approach online sales.</blockquote><div class="flex items-center justify-center gap-4"><div class="w-12 h-12 bg-gray-200 rounded-full flex items-center justify-center"><span class="text-xs text-gray-400">Photo</span></div><div class="text-left"><p class="font-bold text-gray-900 text-sm">Sarah Chen</p><p class="text-gray-500 text-xs">Founder, Blank Studio</p></div></div></div></section>` },
  { id: "text-4", label: "Text + Image", category: "Text", content: `<section class="w-full bg-white py-16 px-6"><div class="max-w-7xl mx-auto grid md:grid-cols-2 gap-12 items-center"><div><h2 class="text-3xl font-bold text-gray-900 mb-6">Our Story</h2><p class="text-gray-600 mb-4 leading-relaxed">We started with a simple idea: make commerce beautiful and accessible.</p><p class="text-gray-600 leading-relaxed">Today, thousands of creators trust us to power their online presence.</p></div><div class="bg-gray-100 rounded-2xl aspect-[4/3] flex items-center justify-center"><span class="text-gray-400 text-sm">Image</span></div></div></section>` },
  { id: "text-5", label: "Stats Row", category: "Text", content: `<section class="w-full bg-gray-900 text-white py-16 px-6"><div class="max-w-7xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8 text-center"><div><p class="text-3xl md:text-4xl font-black text-white mb-2">10K+</p><p class="text-white/60 text-sm">Merchants</p></div><div><p class="text-3xl md:text-4xl font-black text-white mb-2">$2M+</p><p class="text-white/60 text-sm">GMV Processed</p></div><div><p class="text-3xl md:text-4xl font-black text-white mb-2">99.9%</p><p class="text-white/60 text-sm">Uptime</p></div><div><p class="text-3xl md:text-4xl font-black text-white mb-2">4.9</p><p class="text-white/60 text-sm">App Store Rating</p></div></div></section>` },

  /* ── Image/Video ── */
  { id: "media-1", label: "Full Image", category: "Image/Video", content: `<section class="w-full"><div class="w-full aspect-[21/9] bg-gray-200 flex items-center justify-center relative"><span class="text-gray-400 text-sm">Image</span></div></section>` },
  { id: "media-2", label: "2 Images", category: "Image/Video", content: `<section class="w-full bg-white py-12 px-6"><div class="max-w-7xl mx-auto grid md:grid-cols-2 gap-6"><div class="aspect-[4/3] bg-gray-200 rounded-2xl flex items-center justify-center"><span class="text-gray-400 text-sm">Image 1</span></div><div class="aspect-[4/3] bg-gray-200 rounded-2xl flex items-center justify-center"><span class="text-gray-400 text-sm">Image 2</span></div></div></section>` },
  { id: "media-3", label: "3 Images", category: "Image/Video", content: `<section class="w-full bg-white py-12 px-6"><div class="max-w-7xl mx-auto grid md:grid-cols-3 gap-6"><div><div class="aspect-[3/4] bg-gray-200 rounded-2xl mb-4 flex items-center justify-center"><span class="text-gray-400 text-xs">Image 1</span></div><p class="text-sm font-medium text-gray-900 text-center">Caption 1</p></div><div><div class="aspect-[3/4] bg-gray-200 rounded-2xl mb-4 flex items-center justify-center"><span class="text-gray-400 text-xs">Image 2</span></div><p class="text-sm font-medium text-gray-900 text-center">Caption 2</p></div><div><div class="aspect-[3/4] bg-gray-200 rounded-2xl mb-4 flex items-center justify-center"><span class="text-gray-400 text-xs">Image 3</span></div><p class="text-sm font-medium text-gray-900 text-center">Caption 3</p></div></div></section>` },
  { id: "media-4", label: "Video Player", category: "Image/Video", content: `<section class="w-full bg-gray-900 py-16 px-6"><div class="max-w-5xl mx-auto text-center"><h2 class="text-3xl font-bold text-white mb-8">See It In Action</h2><div class="aspect-video bg-gray-800 rounded-2xl flex items-center justify-center relative overflow-hidden"><span class="text-gray-500 text-sm">Video Placeholder</span><div class="absolute inset-0 flex items-center justify-center"><div class="w-16 h-16 bg-white/20 rounded-full flex items-center justify-center backdrop-blur-sm"><svg class="w-6 h-6 text-white ml-1" fill="currentColor" viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg></div></div></div></div></section>` },
  { id: "media-5", label: "Gallery Grid", category: "Image/Video", content: `<section class="w-full bg-white py-12 px-6"><div class="max-w-7xl mx-auto"><div class="grid grid-cols-2 md:grid-cols-3 gap-4"><div class="col-span-2 row-span-2 bg-gray-200 rounded-2xl flex items-center justify-center relative"><span class="text-gray-400 text-sm">Main Image</span><div class="absolute bottom-6 left-6"><h3 class="text-white font-bold text-xl">Collection</h3></div></div><div class="bg-gray-100 rounded-2xl aspect-square flex items-center justify-center"><span class="text-gray-300 text-xs">Img</span></div><div class="bg-gray-100 rounded-2xl aspect-square flex items-center justify-center"><span class="text-gray-300 text-xs">Img</span></div><div class="bg-gray-100 rounded-2xl aspect-square flex items-center justify-center"><span class="text-gray-300 text-xs">Img</span></div><div class="bg-gray-100 rounded-2xl aspect-square flex items-center justify-center"><span class="text-gray-300 text-xs">Img</span></div></div></div></section>` },

  /* ── Footers ── */
  { id: "footer-1", label: "Simple Links", category: "Footer", content: `<footer class="w-full bg-gray-50 border-t border-gray-200 py-12 px-6"><div class="max-w-7xl mx-auto grid md:grid-cols-4 gap-8"><div class="md:col-span-1"><div class="text-xl font-bold text-gray-900 mb-4">Brand</div><p class="text-sm text-gray-500">Building the future of commerce.</p></div><div><h4 class="font-bold text-gray-900 text-sm mb-4">Shop</h4><ul class="space-y-2 text-sm text-gray-500"><li><a href="#" class="hover:text-gray-900">Link</a></li><li><a href="#" class="hover:text-gray-900">Link</a></li><li><a href="#" class="hover:text-gray-900">Link</a></li></ul></div><div><h4 class="font-bold text-gray-900 text-sm mb-4">Company</h4><ul class="space-y-2 text-sm text-gray-500"><li><a href="#" class="hover:text-gray-900">Link</a></li><li><a href="#" class="hover:text-gray-900">Link</a></li><li><a href="#" class="hover:text-gray-900">Link</a></li></ul></div><div><h4 class="font-bold text-gray-900 text-sm mb-4">Support</h4><ul class="space-y-2 text-sm text-gray-500"><li><a href="#" class="hover:text-gray-900">Link</a></li><li><a href="#" class="hover:text-gray-900">Link</a></li><li><a href="#" class="hover:text-gray-900">Link</a></li></ul></div></div><div class="max-w-7xl mx-auto mt-12 pt-8 border-t border-gray-200 text-sm text-gray-400 flex justify-between"><span>(c) 2025 Brand</span><span>Privacy &middot; Terms</span></div></footer>` },
  { id: "footer-2", label: "Dark Minimal", category: "Footer", content: `<footer class="w-full bg-gray-900 text-white py-12 px-6"><div class="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6"><div class="text-xl font-bold">Brand</div><nav class="flex gap-8 text-sm text-white/60"><a href="#" class="hover:text-white">Home</a><a href="#" class="hover:text-white">Shop</a><a href="#" class="hover:text-white">About</a><a href="#" class="hover:text-white">Contact</a></nav><div class="text-sm text-white/40">(c) 2025</div></div></footer>` },
  { id: "footer-3", label: "Newsletter", category: "Footer", content: `<footer class="w-full bg-white border-t border-gray-200 py-16 px-6"><div class="max-w-7xl mx-auto grid md:grid-cols-2 gap-12 items-center mb-12"><div><h3 class="text-2xl font-bold text-gray-900 mb-3">Stay in the loop</h3><p class="text-gray-500">New products, exclusive drops, and insider offers.</p></div><div class="flex gap-3"><input type="email" placeholder="Email address" class="flex-1 px-4 py-3 border border-gray-300 rounded-lg text-sm"/><button class="bg-black text-white px-6 py-3 rounded-lg text-sm font-medium">Subscribe</button></div></div><div class="max-w-7xl mx-auto pt-10 border-t border-gray-200 flex justify-between text-sm text-gray-400"><span>(c) 2025 Brand</span><div class="flex gap-6"><a href="#">Privacy</a><a href="#">Terms</a></div></div></footer>` },
  { id: "footer-4", label: "Mega Footer", category: "Footer", content: `<footer class="w-full bg-gray-50 py-16 px-6"><div class="max-w-7xl mx-auto grid grid-cols-2 md:grid-cols-5 gap-8 mb-12"><div class="col-span-2"><div class="text-2xl font-black text-gray-900 mb-4">Marketplace</div><p class="text-sm text-gray-500 mb-6">Empowering the next generation of online sellers.</p><div class="flex gap-4"><div class="w-8 h-8 bg-gray-200 rounded-full"></div><div class="w-8 h-8 bg-gray-200 rounded-full"></div><div class="w-8 h-8 bg-gray-200 rounded-full"></div></div></div><div><h4 class="font-bold text-gray-900 text-sm mb-4">Products</h4><ul class="space-y-2 text-sm text-gray-500"><li><a href="#">Link</a></li><li><a href="#">Link</a></li><li><a href="#">Link</a></li><li><a href="#">Link</a></li></ul></div><div><h4 class="font-bold text-gray-900 text-sm mb-4">Company</h4><ul class="space-y-2 text-sm text-gray-500"><li><a href="#">Link</a></li><li><a href="#">Link</a></li><li><a href="#">Link</a></li><li><a href="#">Link</a></li></ul></div><div><h4 class="font-bold text-gray-900 text-sm mb-4">Resources</h4><ul class="space-y-2 text-sm text-gray-500"><li><a href="#">Link</a></li><li><a href="#">Link</a></li><li><a href="#">Link</a></li><li><a href="#">Link</a></li></ul></div><div><h4 class="font-bold text-gray-900 text-sm mb-4">Legal</h4><ul class="space-y-2 text-sm text-gray-500"><li><a href="#">Link</a></li><li><a href="#">Link</a></li><li><a href="#">Link</a></li><li><a href="#">Link</a></li></ul></div></div><div class="max-w-7xl mx-auto pt-8 border-t border-gray-200 text-xs text-gray-400 text-center">(c) 2025 Marketplace Inc. All rights reserved.</div></footer>` },
  { id: "footer-5", label: "Centered Social", category: "Footer", content: `<footer class="w-full bg-white py-16 px-6 text-center"><div class="max-w-xl mx-auto"><div class="text-2xl font-bold text-gray-900 mb-6">Brand</div><nav class="flex justify-center gap-8 text-sm text-gray-500 mb-8"><a href="#" class="hover:text-gray-900">Shop</a><a href="#" class="hover:text-gray-900">About</a><a href="#" class="hover:text-gray-900">Contact</a><a href="#" class="hover:text-gray-900">FAQ</a></nav><div class="flex justify-center gap-4 mb-8"><div class="w-10 h-10 bg-gray-100 rounded-full flex items-center justify-center text-xs text-gray-400">IG</div><div class="w-10 h-10 bg-gray-100 rounded-full flex items-center justify-center text-xs text-gray-400">X</div><div class="w-10 h-10 bg-gray-100 rounded-full flex items-center justify-center text-xs text-gray-400">YT</div></div><p class="text-xs text-gray-400">(c) 2025 Brand. All rights reserved.</p></div></footer>` },
]

export function getBlocksByCategory() {
  const cats: Record<string, BlockMeta[]> = {}
  BLOCKS_META.forEach((b) => {
    cats[b.category] = cats[b.category] || []
    cats[b.category].push(b)
  })
  return cats
}
